"""
Pydantic models for the Knowledge Base Web Importer application.
"""

import json
from typing import Optional
from urllib.parse import quote_plus, urljoin, urlparse, parse_qs

from pydantic import BaseModel, field_validator


def extract_youtube_video_id(url: str) -> Optional[str]:
    """Helper to parse out YouTube video ID from various link structures."""
    try:
        parsed = urlparse(url)
        if parsed.hostname in ("youtu.be", "www.youtu.be"):
            return parsed.path.lstrip("/")
        if parsed.hostname in ("youtube.com", "www.youtube.com", "m.youtube.com"):
            if parsed.path == "/watch":
                return parse_qs(parsed.query).get("v", [None])[0]
            if parsed.path.startswith(("/embed/", "/v/")):
                return parsed.path.split("/")[2]
    except Exception:
        pass
    return None


class YouTubeVideoMetadata(BaseModel):
    """Pydantic model representing metadata for a YouTube video page."""

    url: str
    video_id: str
    creator: str
    channel_id: Optional[str] = None
    duration: Optional[int] = None
    view_count: Optional[int] = None
    thumbnail_url: Optional[str] = None
    updated_at: str



class ParsedUrl(BaseModel):
    """Pydantic model representing decomposed parts of a URL.

    Provides components like scheme, netloc, and fragments.
    """

    scheme: str
    netloc: str
    path: Optional[str] = None
    fragments: Optional[str] = None
    query: Optional[str] = None
    port: Optional[int] = None
    hostname: Optional[str] = None

    @classmethod
    def from_url(cls, url: str) -> "ParsedUrl":
        """Deconstructs a string URL into structured ParsedUrl components.

        Args:
            url (str): String representing the full URL.

        Returns:
            ParsedUrl: Instance containing parsed URL attributes.
        """
        parsed = urlparse(url)
        return cls(
            scheme=parsed.scheme,
            netloc=parsed.netloc,
            path=parsed.path,
            fragments=parsed.fragment,
            query=parsed.query,
            port=parsed.port,
            hostname=parsed.hostname,
        )


class HTMLPage(BaseModel):
    """Pydantic model representing a scraped web page.

    Contains full raw HTML, converted Markdown, metadata, and extracted links.
    """

    url: str
    title: Optional[str] = None  # Page Title assigned during wiki extraction
    html_content: str
    md_content: str
    links: list[str]
    html_content_hash: str
    md_content_hash: str
    fetched_at: str
    description: Optional[str] = None
    keywords: Optional[list[str]] = None
    tags: Optional[list[str]] = (
        None  # Array of descriptive tags generated by Ollama/user
    )

    @field_validator("links", mode="before")
    @classmethod
    def ensure_links_list(cls, v, info) -> list[str]:
        """Validates and cleans the link list, resolving relative URLs to

        absolute ones under the base URL.

        Args:
            v: Input link parameter (JSON string or list).
            info: Validator field info containing page attributes.

        Returns:
            list[str]: Normalized absolute links.
        """
        url = info.data.get("url", "")
        if isinstance(v, str):
            try:
                links_list = json.loads(v)
                if isinstance(links_list, list):
                    return [
                        urljoin(url, link) if link.startswith("/") else link
                        for link in links_list
                    ]
            except json.JSONDecodeError:
                return [urljoin(url, v) if v.startswith("/") else v]
        if isinstance(v, list):
            return [
                (
                    urljoin(url, link)
                    if isinstance(link, str) and link.startswith("/")
                    else link
                )
                for link in v
            ]
        return v or []

    @field_validator("keywords", mode="before")
    @classmethod
    def ensure_keywords_list(cls, v) -> list[str]:
        """Ensures that keywords input is parsed into a list of strings.

        Args:
            v: Input keyword parameter (JSON string or list).

        Returns:
            list[str]: Deserialized keyword list.
        """
        if isinstance(v, str):
            try:
                keywords_list = json.loads(v)
                if isinstance(keywords_list, list):
                    return keywords_list
            except json.JSONDecodeError:
                return [v]
        return v or []

    @field_validator("tags", mode="before")
    @classmethod
    def ensure_tags_list(cls, v) -> list[str]:
        """Ensures that tags input is parsed into a list of strings.

        Args:
            v: Input tags parameter (JSON string or list).

        Returns:
            list[str]: Deserialized tags list.
        """
        if isinstance(v, str):
            try:
                tags_list = json.loads(v)
                if isinstance(tags_list, list):
                    return tags_list
            except json.JSONDecodeError:
                return [v]
        elif isinstance(v, list):
            return [str(item) for item in v if item]
        return v or []

    @property
    def safe_url(self) -> str:
        """URL-encoded variant of the page URL for safe query param transport.

        Returns:
            str: URL-encoded string.
        """
        return quote_plus(self.url)

    @property
    def base_url(self) -> str:
        """Constructs the base origin URL (scheme + netloc) of the page.

        Returns:
            str: Origin URL (e.g. https://example.com).
        """
        parsed = urlparse(self.url)
        return f"{parsed.scheme}://{parsed.netloc}"

    @property
    def parsed_url(self) -> ParsedUrl:
        """Returns deconstructed components as a ParsedUrl class.

        Returns:
            ParsedUrl: Structured components.
        """
        return ParsedUrl.from_url(self.url)
